#metrics
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator  # Рекомендуется явно указать базовый путь
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    health:
      show-details: always  # Для более детальной информации о здоровье
  prometheus:
    metrics:
      export:
        enabled: true

#swagger
xset:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://xset-api.com

#database
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true  # Включено для отладки (можно отключить после)
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres  # Исправлено с localhost на postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000  # Увеличенный таймаут для Docker
  #uploads
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #kafka
  kafka:
    bootstrap-servers: kafka:9092  # Общее свойство для producer/consumer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: yourGroupId
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual  # Для явного управления квитированием
    template:
      default-topic: my-default-topic
# Дополнительные настройки
server:
  port: 8080
  shutdown: graceful  # Для корректного завершения работы

#JMX
#-Dcom.sun.management.jmxremote
#-Dcom.sun.management.jmxremote.port=YOUR_JMX_PORT
#-Dcom.sun.management.jmxremote.rmi.port=YOUR_JMX_PORT
#-Dcom.sun.management.jmxremote.authenticate=false
#-Dcom.sun.management.jmxremote.ssl=false
#-Djava.rmi.server.hostname=YOUR_JMX_HOST