scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'LT app'

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
        labels:
          application: 'LT server'
